Python 本身支持的数值类型有 int（整型）、float（浮点型）、bool（布尔型） 和 complex（复数型）

在 NumPy 中，数值类型都被归于 dtype（data-type） 对象的实例。 我们可以用 numpy.dtype(object, align, copy) 来指定数值类型。而在数组里面，可以用 dtype= 参数。

In [1]:
# 导入 NumPy 模块
import numpy as np  

In [2]:
# 指定 1 维数组的数值类型为 float64
a = np.array([1.1, 2.2, 3.3], dtype=np.float64)  

# 查看 a 及 dtype 类型
a, a.dtype  

(array([1.1, 2.2, 3.3]), dtype('float64'))

In [3]:
# 将 a 的数值类型从 float64 转换为 int，并查看 dtype 类型
a.astype(int).dtype  

dtype('int32')

# Numpy数组生成

在 Python 内建对象中，数组有三种形式：

- 列表：[1, 2, 3]
- 元组：(1, 2, 3, 4, 5)
- 字典：{A:1, B:2}

### 创建数组的5种途径

- 从 Python 数组结构列表，元组等转换。
- 使用 np.arange、np.ones、np.zeros 等 NumPy 原生方法。
- 从存储空间读取数组。
- 通过使用字符串或缓冲区从原始字节创建数组。
- 使用特殊函数，如 random。

array方法创建

In [6]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.array([(1, 2), (3, 4), (5, 6)])

array([[1, 2],
       [3, 4],
       [5, 6]])

arange方法创建

In [8]:
# 在区间 [3, 7) 中以 0.5 为步长新建数组
np.arange(3, 7, 0.5, dtype='float32')

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5], dtype=float32)

linspace方法创建

In [9]:
np.linspace(0, 10, 10, endpoint=True)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [10]:
np.linspace(0, 10, 10, endpoint=False)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

ones方法创建

In [11]:
# 第一个是行，第二个是列
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

zeros方法创建

In [12]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

eye方法创建

In [17]:
np.eye(5, 4, 3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

从已知数据创建

In [18]:
np.fromfunction(lambda a, b: a + b, (5, 4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.],
       [4., 5., 6., 7.]])

### ndarray数组属性

In [19]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

数组转置

In [20]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

数据类型

In [21]:
a.dtype

dtype('int32')

虚部

In [22]:
a.imag

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

实部

In [23]:
a.real

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

总包含元素数

In [25]:
a.size

9

字节数

In [26]:
a.itemsize

4

总字节数

In [27]:
a.nbytes

36

数组维度

In [28]:
a.ndim

2

数组形状

In [29]:
a.shape

(3, 3)

### 数组维度和形状

In [31]:
one = np.array([7, 2, 9, 10])
two = np.array([[5.2, 3.0, 4.5],
                [9.1, 0.1, 0.3]])
three = np.array([[[1, 1], [1, 1], [1, 1]],
                  [[1, 1], [1, 1], [1, 1]],
                  [[1, 1], [1, 1], [1, 1]],
                  [[1, 1], [1, 1], [1, 1]]])

In [32]:
one.shape, two.shape, three.shape

((4,), (2, 3), (4, 3, 2))

# 数组基本操作

### 重设形状

In [33]:
np.arange(10).reshape((5, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### 数组展开

In [35]:
a = np.arange(10).reshape((2, 5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
np.ravel(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
# 按列展开
np.ravel(a, order='F')

array([0, 5, 1, 6, 2, 7, 3, 8, 4, 9])

### 轴移动

In [38]:
a = np.ones((1, 2, 3))
np.moveaxis(a, 0, -1)

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [41]:
a.shape, np.moveaxis(a, 0, -1).shape

((1, 2, 3), (2, 3, 1))

### 轴交换

In [42]:
a = np.ones((1, 4, 3))
np.swapaxes(a, 0, 2)

array([[[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]]])

### 数组转置

In [43]:
a = np.arange(4).reshape(2, 2)
np.transpose(a)

array([[0, 2],
       [1, 3]])

In [44]:
a.T

array([[0, 2],
       [1, 3]])

### 维度改变

In [45]:
print(np.atleast_1d([1, 2, 3]))
print(np.atleast_2d([4, 5, 6]))
print(np.atleast_3d([7, 8, 9]))

[1 2 3]
[[4 5 6]]
[[[7]
  [8]
  [9]]]


### 类型转换

In [46]:
a = np.arange(4).reshape(2, 2)

# 将二维数组转化为矩阵类型
np.asmatrix(a)  

matrix([[0, 1],
        [2, 3]])

### 数组连接

In [47]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[7, 8], [9, 10]])
c = np.array([[11, 12]])

np.concatenate((a,b,c), axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [48]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[7, 8, 9]])

np.concatenate((a, b.T), axis=1)

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

### 数组堆叠

In [49]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.stack((a, b), axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

### 数组拆分

In [51]:
a = np.arange(10)
np.split(a, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [52]:
a = np.arange(10).reshape(2, 5)
np.split(a, 2)

[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]

### 数组删除

In [53]:
a = np.arange(12).reshape(3, 4)
np.delete(a, 2, 1)

array([[ 0,  1,  3],
       [ 4,  5,  7],
       [ 8,  9, 11]])

In [54]:
np.delete(a, 2, 0)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### 数组插入

In [55]:
a = np.arange(12).reshape(3, 4)
b = np.arange(4)

np.insert(a, 2, b, 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

### 数组附加

In [56]:
a = np.arange(6).reshape(2, 3)
b = np.arange(3)

np.append(a, b)

array([0, 1, 2, 3, 4, 5, 0, 1, 2])

### 重设尺寸

reshape 在改变形状时，不会影响原数组，相当于对原数组做了一份拷贝。而 resize 则是对原数组执行操作

In [57]:
a = np.arange(10)
a.resize(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 数组翻转

In [59]:
a = np.arange(16).reshape(4, 4)

# 左右翻转
print(np.fliplr(a))

# 上下翻转
print(np.flipud(a))

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


# 随机数

In [60]:
# [0, 1) 区间随机数
np.random.rand(2, 5)

array([[0.78162938, 0.07990332, 0.12653719, 0.40282272, 0.05413063],
       [0.16044719, 0.4412722 , 0.52137876, 0.86714515, 0.56869657]])

In [62]:
# 标准正态分布中返回一个或多个样本值
np.random.randn(1, 10)

array([[-0.45936087, -0.1515481 , -0.5936838 , -0.61332733, -0.18913633,
        -0.32680436, -1.28486395,  0.69940439,  1.15618682, -0.83035949]])

In [63]:
# [low, high) 的随机整数
np.random.randint(2, 5, 10)

array([3, 4, 3, 2, 3, 2, 2, 3, 4, 3])

In [64]:
# [0, 1) 区间内生成指定 size 的随机浮点数
np.random.random_sample([10])

array([0.38787998, 0.00473074, 0.5765139 , 0.36363998, 0.090598  ,
       0.81752736, 0.67668631, 0.62756022, 0.303945  , 0.95790772])

随机抽样

In [65]:
np.random.choice(10, 5)

array([7, 5, 2, 1, 8])

# 数学函数

三角函数

In [67]:
# PI 值弧度表示
np.rad2deg(np.pi)  

180.0

数值修约

In [68]:
a = np.random.randn(5)  
a  

array([-1.10629416,  1.86813407, -0.70306111, -1.04873915,  0.93194496])

In [71]:
# 平均到给定的小数位数
np.around(a, 2)

array([-1.11,  1.87, -0.7 , -1.05,  0.93])

In [72]:
# 修约到最接近的整数
np.rint(a)

array([-1.,  2., -1., -1.,  1.])

In [74]:
# 向 0 舍入到最接近的整数
np.fix(a)

array([-1.,  1., -0., -1.,  0.])

求和、求积、差分

In [75]:
a = np.arange(10) 
a  

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.sum(a)

45

In [77]:
np.diff(a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

算术运算

In [84]:
a1 = np.random.randint(0, 10, 5)  
a2 = np.random.randint(0, 10, 5)
a1, a2  

(array([9, 1, 5, 5, 7]), array([8, 3, 5, 2, 8]))

In [85]:
np.add(a1, a2)

array([17,  4, 10,  7, 15])

In [90]:
np.subtract(a1, a2)

array([ 1, -2,  0,  3, -1])

In [86]:
np.negative(a1)

array([-9, -1, -5, -5, -7])

In [87]:
np.multiply(a1, a2)

array([72,  3, 25, 10, 56])

In [88]:
np.divide(a1, a2)

array([1.125     , 0.33333333, 1.        , 2.5       , 0.875     ])

In [89]:
np.power(a1, a2)

array([43046721,        1,     3125,       25,  5764801], dtype=int32)

矩阵和向量积

In [91]:
a = np.matrix([[1, 2, 3], [4, 5, 6]])
b = np.matrix([[2, 2], [3, 3], [4, 4]])

np.matmul(a, b)

matrix([[20, 20],
        [47, 47]])

# 数组索引和切片

### 数组索引

In [92]:
a = np.arange(10)  
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
a[1]

1

In [94]:
a[[1, 2, 3]]

array([1, 2, 3])

二维数据

In [95]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [96]:
a[1, 2]

7

使用python list

In [97]:
a = a.tolist()
a

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]]

In [98]:
a[1,  2]

TypeError: list indices must be integers or slices, not tuple

In [99]:
a[1][2]

7

索引二维 Ndarray 中的多个元素值

In [100]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [101]:
a[[1, 2], [3, 4]]

array([ 8, 14])

三维数据

In [102]:
a = np.arange(30).reshape(2, 5, 3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [103]:
a[[0, 1], [1, 2], [1, 2]]

array([ 4, 23])

### 数据切片

In [104]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
a[:5]

array([0, 1, 2, 3, 4])

In [106]:
a[5:10]

array([5, 6, 7, 8, 9])

In [107]:
a[0:10:2]

array([0, 2, 4, 6, 8])

多维数组切片

In [108]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [109]:
a[0:3, 2:4]

array([[ 2,  3],
       [ 7,  8],
       [12, 13]])

In [110]:
a[:, ::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19]])

# 排序、搜索、计数

### 排序

In [111]:
a = np.random.rand(20).reshape(4, 5)
a

array([[0.22205137, 0.26730161, 0.30271461, 0.8131046 , 0.7848524 ],
       [0.64222731, 0.80831436, 0.75488064, 0.7601936 , 0.53036135],
       [0.31353656, 0.09780888, 0.60035169, 0.39676002, 0.86708764],
       [0.59833953, 0.29196298, 0.60751693, 0.42651638, 0.78212188]])

In [112]:
np.sort(a)

array([[0.22205137, 0.26730161, 0.30271461, 0.7848524 , 0.8131046 ],
       [0.53036135, 0.64222731, 0.75488064, 0.7601936 , 0.80831436],
       [0.09780888, 0.31353656, 0.39676002, 0.60035169, 0.86708764],
       [0.29196298, 0.42651638, 0.59833953, 0.60751693, 0.78212188]])

### 搜索和计数

In [113]:
a = np.random.randint(0, 10, 20)
a

array([1, 5, 9, 4, 4, 9, 8, 3, 7, 2, 9, 5, 2, 0, 9, 2, 5, 0, 6, 7])

In [114]:
# 返回数组中指定轴的最大值的索引
np.argmax(a)

2

In [115]:
# 返回数组中指定轴的最小值的索引
np.argmin(a)

13

In [117]:
# 返回数组中非 0 元素的索引
np.nonzero(a)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 14, 15, 16, 18,
        19], dtype=int64),)

In [118]:
# 计算数组中非 0 元素的数量
np.count_nonzero(a)

18