In [1]:
import numpy as np

In [2]:
# 查看版本信息
np.__version__

'1.18.1'

# 创建数组

通过列表创建一维数组

In [3]:
# Rank (秩)为1
np.array([1,2,3])

array([1, 2, 3])

通过列表创建二维数组

In [4]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

创建全为 0 的二维数组

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

创建全为 1 的三维数组

In [7]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

创建一维等差数组

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

创建二维等差数组

In [9]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

创建单位矩阵（二维数组）

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

创建等间隔一维数组

In [11]:
np.linspace(1, 10, num=6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

创建二维随机数组

In [12]:
np.random.rand(2,3)

array([[0.89932612, 0.99970928, 0.75450493],
       [0.25557653, 0.74414039, 0.44982133]])

创建二维随机整数数组（数值小于 5）

In [13]:
np.random.randint(5, size=(2,3))

array([[4, 1, 3],
       [3, 2, 2]])

依据自定义函数创建数组

In [14]:
np.fromfunction(lambda i, j: i + j, (3, 3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

# 数组运算

生成一维示例数组

In [18]:
a = np.arange(10, 51, 10)
b = np.arange(1,6)

a, b

(array([10, 20, 30, 40, 50]), array([1, 2, 3, 4, 5]))

In [19]:
a + b

array([11, 22, 33, 44, 55])

In [20]:
a - b

array([ 9, 18, 27, 36, 45])

In [21]:
a * b

array([ 10,  40,  90, 160, 250])

In [22]:
a / b

array([10., 10., 10., 10., 10.])

生成二维示例数组

In [23]:
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])

A, B

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [24]:
A + B

array([[ 6,  8],
       [10, 12]])

In [25]:
A - B

array([[-4, -4],
       [-4, -4]])

In [26]:
# 矩阵元素间乘法
A * B

array([[ 5, 12],
       [21, 32]])

In [27]:
# 矩阵乘法
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [28]:
np.mat(A) * np.mat(B)

matrix([[19, 22],
        [43, 50]])

In [29]:
2 * A

array([[2, 4],
       [6, 8]])

In [31]:
# 转置
A.T

array([[1, 3],
       [2, 4]])

In [32]:
# 求逆
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# 数学函数

三角函数

In [34]:
print(a)
np.sin(a)

[10 20 30 40 50]


array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

以自然对数函数为底数的指数函数

In [35]:
np.exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])

开方

In [36]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

求3次方

In [37]:
np.power(a, 3)

array([  1000,   8000,  27000,  64000, 125000], dtype=int32)

# 数组切片和索引

一维数组索引

In [42]:
a = np.arange(1, 6)
a[0], a[-1]

(1, 5)

一维数组切片

In [44]:
a[0:2], a[:-1]

(array([1, 2]), array([1, 2, 3, 4]))

二维数组索引

In [48]:
a = np.arange(1, 10).reshape(3,3)
a[0], a[-1]

(array([1, 2, 3]), array([7, 8, 9]))

二维数组切片

In [49]:
print(a)

a[:, 1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2, 5, 8])

In [50]:
a[1:3, :]

array([[4, 5, 6],
       [7, 8, 9]])

# 数组形状操作

生成二维示例数组

In [51]:
a = np.random.random((3,2))

In [52]:
a

array([[0.37060093, 0.23237346],
       [0.50917112, 0.71406794],
       [0.62869301, 0.90045211]])

In [53]:
# 查看形状
a.shape

(3, 2)

In [54]:
# 更改形状（不改变原始数组）
a.reshape(2,3)

array([[0.37060093, 0.23237346, 0.50917112],
       [0.71406794, 0.62869301, 0.90045211]])

In [55]:
a

array([[0.37060093, 0.23237346],
       [0.50917112, 0.71406794],
       [0.62869301, 0.90045211]])

In [56]:
# 更改形状（改变原始数组）
a.resize(2,3)

In [57]:
a

array([[0.37060093, 0.23237346, 0.50917112],
       [0.71406794, 0.62869301, 0.90045211]])

In [59]:
# 展平数组
a.ravel()

array([0.37060093, 0.23237346, 0.50917112, 0.71406794, 0.62869301,
       0.90045211])

In [60]:
a = np.random.randint(10, size=(3,3))
b = np.random.randint(10, size=(3,3))

a, b

(array([[3, 0, 1],
        [3, 2, 8],
        [2, 9, 4]]),
 array([[0, 3, 5],
        [0, 0, 2],
        [4, 6, 3]]))

In [61]:
# 垂直拼合数组
np.vstack((a,b))

array([[3, 0, 1],
       [3, 2, 8],
       [2, 9, 4],
       [0, 3, 5],
       [0, 0, 2],
       [4, 6, 3]])

In [62]:
# 水平拼合数组
np.hstack((a,b))

array([[3, 0, 1, 0, 3, 5],
       [3, 2, 8, 0, 0, 2],
       [2, 9, 4, 4, 6, 3]])

In [63]:
# 沿横轴分割数组
np.hsplit(a, 3)

[array([[3],
        [3],
        [2]]),
 array([[0],
        [2],
        [9]]),
 array([[1],
        [8],
        [4]])]

In [64]:
# 沿纵轴分割数组
np.vsplit(a, 3)

[array([[3, 0, 1]]), array([[3, 2, 8]]), array([[2, 9, 4]])]

# 数组排序

In [65]:
a = np.array(([1, 4, 3], [6, 2, 9], [4, 7, 2]))
a

array([[1, 4, 3],
       [6, 2, 9],
       [4, 7, 2]])

In [67]:
# 返回每列最大值
np.max(a, axis=0)

array([6, 7, 9])

In [68]:
# 返回每行最小值
np.min(a, axis=1)

array([1, 2, 2])

In [69]:
# 返回每列最大值索引
np.argmax(a, axis=0)

array([1, 2, 1], dtype=int64)

In [70]:
# 返回每行最小值索引
np.argmin(a, axis=1)

array([0, 1, 2], dtype=int64)

# 数组统计

In [71]:
# 各列中位数
np.median(a, axis=0)

array([4., 4., 3.])

In [72]:
# 各行的算数平均数
np.mean(a, axis=1)

array([2.66666667, 5.66666667, 4.33333333])

In [73]:
# 各列的加权平均数
np.average(a, axis=0)

array([3.66666667, 4.33333333, 4.66666667])

In [74]:
# 各行的方差
np.var(a, axis=1)

array([1.55555556, 8.22222222, 4.22222222])

In [75]:
# 各列的标准差
np.std(a, axis=0)

array([2.05480467, 2.05480467, 3.09120617])